// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hidcxkasdmziyfdwmeap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZGN4a2FzZG16aXlmZHdtZWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzA3MTQsImV4cCI6MjA3MDUwNjcxNH0.wi81PaDh4HFopXoT_fCRuPLjg_ZyDIHER9_G8AjsnbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});